<a href="https://colab.research.google.com/github/siddhantmohan1110/DLTA_PA_1/blob/master/cifar10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch 
from sklearn.metrics import confusion_matrix, accuracy_score

(x_train_raw, y_train, x_test_raw, y_test)=torch.load('cifar10.pt') #Loaded the dataset

In [0]:
train_size=x_train_raw.size()[0]
test_size=x_test_raw.size()[0] #Finding size of training and test data

In [0]:
x_train=torch.zeros(train_size,768);
x_test=torch.zeros(test_size,768);
x_train_raw=x_train_raw.float()
x_test_raw=x_test_raw.float() 

for i in range(train_size): #Computing histogram  for training data
  torch.histc(x_train_raw[i,:,:,0],bins=256,min=0,max=255,out=x_train[i,:256])
  torch.histc(x_train_raw[i,:,:,1],bins=256,min=0,max=255,out=x_train[i,256:512])
  torch.histc(x_train_raw[i,:,:,2],bins=256,min=0,max=255,out=x_train[i,512:768])
  
for i in range(test_size): #Computing histogram for test data
  torch.histc(x_test_raw[i,:,:,0],bins=256,min=0,max=255,out=x_test[i,:256])
  torch.histc(x_test_raw[i,:,:,1],bins=256,min=0,max=255,out=x_test[i,256:512])
  torch.histc(x_test_raw[i,:,:,2],bins=256,min=0,max=255,out=x_test[i,512:768])

In [0]:
#Function for KNN classificaton
def knn(x_train,y_train,x_test,k=1):
  train_size=x_train.size()[0]
  test_size=x_test.size()[0]
  y_pred=torch.zeros(test_size)
  dist=torch.zeros(train_size)
  for i in range(test_size):
    for j in range(train_size):
      dist[j]=torch.dist(x_test[i,:].float(),x_train[j,:].float()) 
      #Computing Euclidean distance between given test vector and all training vectors 
    nearest=y_train[dist.argsort()[:k]] #Finding k nearest neighbours
    label,freq = torch.unique(nearest,return_counts=True)  #Majority voting among neighbours
    y_pred[i]=label[freq.argsort(descending=True)[0]]  
  return y_pred #Returning predicted classes
  

In [0]:
y_pred_1=knn(x_train,y_train,x_test,1) #k=1

In [9]:
confusion_matrix(y_test,y_pred_1) #Computing confusion matrix

array([[2, 1, 0, 1, 1, 0, 4, 0, 1, 0],
       [0, 2, 0, 0, 0, 1, 0, 0, 1, 2],
       [0, 3, 1, 1, 1, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 1, 2, 1, 0, 4],
       [0, 0, 2, 2, 0, 2, 1, 0, 0, 0],
       [0, 2, 1, 1, 0, 1, 2, 0, 0, 1],
       [0, 0, 0, 3, 3, 0, 8, 2, 0, 0],
       [1, 1, 0, 1, 1, 1, 1, 3, 0, 2],
       [5, 1, 0, 3, 0, 0, 1, 0, 1, 2],
       [0, 2, 0, 1, 1, 1, 1, 0, 1, 4]])

In [10]:
accuracy_score(y_test,y_pred_1) #Computing accuracy score

0.22

In [0]:
y_pred_3=knn(x_train,y_train,x_test,3) #k=3

In [12]:
confusion_matrix(y_test,y_pred_3) #Computing confusion matrix

array([[4, 1, 0, 2, 0, 0, 2, 0, 1, 0],
       [0, 2, 2, 0, 1, 0, 1, 0, 0, 0],
       [1, 2, 2, 0, 1, 0, 1, 1, 0, 0],
       [0, 3, 1, 1, 1, 0, 2, 0, 0, 2],
       [0, 1, 3, 0, 0, 1, 1, 0, 0, 1],
       [0, 3, 2, 2, 0, 0, 0, 0, 0, 1],
       [1, 1, 3, 6, 3, 0, 2, 0, 0, 0],
       [2, 2, 3, 1, 1, 0, 1, 0, 0, 1],
       [5, 4, 1, 1, 0, 0, 0, 0, 1, 1],
       [1, 3, 0, 2, 1, 0, 1, 0, 0, 3]])

In [13]:
accuracy_score(y_test,y_pred_3) #Computing accuracy score

0.15

In [0]:
y_pred_5=knn(x_train,y_train,x_test,5) #k=5

In [15]:
confusion_matrix(y_test,y_pred_5) #Computing confusion matrix

array([[4, 1, 0, 1, 0, 0, 2, 0, 2, 0],
       [1, 2, 1, 0, 2, 0, 0, 0, 0, 0],
       [1, 2, 2, 0, 0, 0, 2, 1, 0, 0],
       [0, 3, 1, 1, 0, 0, 4, 0, 0, 1],
       [0, 0, 3, 0, 0, 1, 2, 0, 0, 1],
       [0, 3, 1, 1, 0, 0, 0, 1, 0, 2],
       [1, 0, 1, 5, 4, 3, 2, 0, 0, 0],
       [4, 2, 2, 0, 1, 0, 1, 0, 0, 1],
       [3, 4, 0, 1, 0, 2, 0, 0, 1, 2],
       [1, 2, 0, 4, 0, 0, 1, 0, 0, 3]])

In [16]:
accuracy_score(y_test,y_pred_5) #Computing accuracy score

0.15