<a href="https://colab.research.google.com/github/siddhantmohan1110/DLTA_PA_1/blob/master/mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
from sklearn.metrics import confusion_matrix, accuracy_score

(x_train, y_train, x_test, y_test)=torch.load('mnist.pt') #Loaded the dataset

In [0]:
x_train.view(-1,784)
x_test.view(-1,784) #Resized the images into 784*1 vector

In [0]:
#Function for KNN classificaton
def knn(x_train,x_test,k=1):
  train_size=x_train.size()[0]
  test_size=x_test.size()[0]
  y_pred=torch.zeros(test_size)
  dist=torch.zeros(train_size)
  for i in range(test_size):
    for j in range(train_size):
      dist[j]=torch.dist(x_test[i,:].float(),x_train[j,:].float()) 
      #Computing Euclidean distance between given test vector and all training vectors 
    nearest=y_train[dist.argsort()[:k]] #Finding k nearest neighbours
    label,freq = torch.unique(nearest,return_counts=True)  #Majority voting among neighbours
    y_pred[i]=label[freq.argsort(descending=True)[0]]  
  return y_pred #Returning predicted classes
  

In [0]:
y_pred_1=knn(x_train,x_test,1) #k=1

In [66]:
confusion_matrix(y_test,y_pred_1) #Computing confusion matrix

array([[ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 14,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  7,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  2,  0,  0,  0,  1],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  4],
       [ 0,  1,  0,  1,  1,  4,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  1],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  1,  0,  9]])

In [67]:
accuracy_score(y_test,y_pred_1) #Computing accuracy score

0.83

In [0]:
y_pred_3=knn(x_train,x_test,3) #k=3

In [69]:
confusion_matrix(y_test,y_pred_3) #Computing confusion matrix

array([[ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 14,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  1,  8,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  4],
       [ 0,  1,  0,  1,  1,  4,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  0,  9]])

In [70]:
accuracy_score(y_test,y_pred_3) #Computing accuracy score

0.83

In [0]:
y_pred_5=knn(x_train,x_test,5) #k=5

In [72]:
confusion_matrix(y_test,y_pred_5) #Computing confusion matrix

array([[ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 14,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  6,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  1,  1,  8,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0, 11,  0,  0,  0,  0,  3],
       [ 0,  1,  0,  1,  1,  4,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  1,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  0,  9]])

In [73]:
accuracy_score(y_test,y_pred_5) #Computing accuracy score

0.84